name: creditpay
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  verification_code_field: ^1.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_native_splash: ^2.4.6
  flutter_lints: ^5.0.0
  
# flutter_native_splash:
#   color: "#ffffff"
#   image: images/creditlogo.png   
#   android: true
#   ios: true
  
  


flutter:

 
  uses-material-design: true

  
  assets:
    - images/
  

  
  fonts:
    - family: montserrat
      fonts:
        - asset: fonts/montserrat-Regular.ttf
        - asset: fonts/montserrat-Bold.ttf
        - asset: fonts/montserrat-italic.ttf
 
 
