
name: creditpay
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  verification_code_field: ^1.1.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.3
  firebase_storage: ^13.0.4
  file_picker: ^10.3.7
  cloudinary_public: ^0.23.1
  cloudinary_url_gen: ^1.8.0
  firebase_auth_platform_interface: ^8.1.5
  http: ^1.6.0
  uuid: ^4.5.1
  flutter_paystack_plus: ^2.3.0
  dropdown_search: ^5.0.6

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/creditlogo.png"
  adaptive_icon_background: "#142B71"
  adaptive_icon_foreground: "images/creditlogo.png"

flutter_native_splash:
  color: "#142B71"          # background color for splash
  image: "images/creditlogo.png"
  # fullscreen: true
  # android_gravity: fill
  android: true
  ios: true
  web: false

  android_12:
    image: "images/creditlogo.png"    # REQUIRED or Android 12 shows black
    icon_background_color: "#142B71"

  


flutter:

 
  uses-material-design: true

  
  assets:
    - images/
  

  
  fonts:
    - family: montserrat
      fonts:
        - asset: fonts/montserrat-Regular.ttf
        - asset: fonts/montserrat-Bold.ttf
        - asset: fonts/montserrat-italic.ttf
 
 
